name: Windward Cams
description: 
author:
  name: Daniel Aakjær Sørensen
  email: hello@windward.life

host: 0.0.0.0

sass:
  sass_dir: assets/css
  style: compressed

collections:
  cams:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: cams
    values:
      layout: cam

permalink: date
highlighter: rouge

gems:
  - jekyll-sitemap

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide
    shortname: windward-cams

include: ['vendor']